# Define the goal
string robot  # name of move_group
string object_name
string assembly_name
geometry_msgs/PoseStamped object_target_pose
string object_frame_to_place  # subframe of the object
float64 approach_object_min_dist
float64 approach_object_max_dist
float64 lift_object_min_dist
float64 lift_object_max_dist
string surface_link  # name of link that owns the surface on witch the object lies before picking
---
# Define the result
bool success
moveit_task_constructor_msgs/Solution solution
---
# Define a feedback message
