# Define the goal
string object_name
string grasp_parameter_location  # The parameter under which grasp information is stored. See Readme for details on the parameter tree structure
geometry_msgs/PoseStamped object_target_pose  # The target pose that the object will be placed at
string object_subframe_to_place   # If defined, the target pose will be set for this subframe instead of the object's frame
bool release_object_after_place
string lift_direction_reference_frame
float64[] lift_direction
string approach_place_direction_reference_frame
float64[] approach_place_direction
string[] robot_names
bool force_robot_order

float64 approach_object_min_dist  # Minimum approach distance in the 'x' direction of the robot hand's frame
float64 approach_object_max_dist  # Maximum approach distance in the 'x' direction of the robot hand's frame
float64 lift_object_min_dist  # Minimum lift distance in the 'z' direction of the world frame
float64 lift_object_max_dist  # Maximum lift distance in the 'z' direction of the world frame
string surface_link  # name of link on which the object lies before picking
---
# Define the result
bool success
moveit_task_constructor_msgs/Solution solution
---
# Define a feedback message
